class customer {
    constructor() {
        this.ID;
        this.OrgID;
        this.CustomerID ;
        this.CustomerIDType ;
        this.ContactNumber ;
        this.NationalID ;
        this.Segment_ID ;
        this.Language_ID ;
        this.CustomerName_L1 ;
        this.CustomerName_L2 ;
        this.CustomerName_L3 ;
        this.CustomerName_L4 ;
        this.Gender_L1 ;
        this.Gender_L2 ;
        this.Gender_L3 ;
        this.Gender_L4 ;
        this.Nationality_L1 ;
        this.Nationality_L2 ;
        this.Nationality_L3 ;
        this.Nationality_L4 ;
        this.CountryOfResidence_L1 ;
        this.CountryOfResidence_L2 ;
        this.CountryOfResidence_L3 ;
        this.CountryOfResidence_L4 ;
        this.StateOfResidence_L1 ;
        this.StateOfResidence_L2 ;
        this.StateOfResidence_L3 ;
        this.StateOfResidence_L4 ;
        this.DateOfBirth ;
        this.Education_L1 ;
        this.Education_L2 ;
        this.Education_L3 ;
        this.Education_L4 ;
        this.Profession_L1 ;
        this.Profession_L2 ;
        this.Profession_L3 ;
        this.Profession_L4 ;
        this.Title_L1 ;
        this.Title_L2 ;
        this.Title_L3 ;
        this.Title_L4 ;
        this.MaritalStatus_L1 ;
        this.MaritalStatus_L2 ;
        this.MaritalStatus_L3 ;
        this.MaritalStatus_L4 ;
        this.Photo = {};
        this.Email ;
        this.CardType ;
        this.CardID ;
        this.CardExpiryDate ;
        this.CI01_Text ;
        this.CI02_Text ;
        this.CI03_Text ;
        this.CI04_Text ;
        this.CI05_Text ;
        this.CI06_Text ;
        this.CI07_Text ;
        this.CI08_Text ;
        this.CI09_Text ;
        this.CI10_Text ;
        this.CI11_Text ;
        this.CI12_Text ;
        this.CI13_Text ;
        this.CI14_Text ;
        this.CI15_Text ;
        this.CI16_Text ;
        this.CI17_Text ;
        this.CI18_Text ;
        this.CI19_Text ;
        this.CI20_Text ;
        this.CI01_Date ;
        this.CI02_Date ;
        this.CI03_Date ;
        this.CI04_Date ;
        this.CI05_Date ;
        this.CI01_Number ;
        this.CI02_Number ;
        this.CI03_Number ;
        this.CI04_Number ;
        this.CI05_Number ;
        this.CreationTime ;
        this.LastUpdateTime ;
    }
}
module.exports = customer;


