class customer {
    constructor() {
        this.id;
        this.org_ID;
        this.customer_ID ;
        this.customerIDType ;
        this.contactNumber ;
        this.national_ID ;
        this.segment_ID ;
        this.language_ID ;
        this.customerName_L1 ;
        this.customerName_L2 ;
        this.customerName_L3 ;
        this.customerName_L4 ;
        this.gender_L1 ;
        this.gender_L2 ;
        this.gender_L3 ;
        this.gender_L4 ;
        this.nationality_L1 ;
        this.nationality_L2 ;
        this.nationality_L3 ;
        this.nationality_L4 ;
        this.countryOfResidence_L1 ;
        this.countryOfResidence_L2 ;
        this.countryOfResidence_L3 ;
        this.countryOfResidence_L4 ;
        this.stateOfResidence_L1 ;
        this.stateOfResidence_L2 ;
        this.stateOfResidence_L3 ;
        this.stateOfResidence_L4 ;
        this.dateOfBirth ;
        this.education_L1 ;
        this.education_L2 ;
        this.education_L3 ;
        this.education_L4 ;
        this.profession_L1 ;
        this.profession_L2 ;
        this.profession_L3 ;
        this.profession_L4 ;
        this.title_L1 ;
        this.title_L2 ;
        this.title_L3 ;
        this.title_L4 ;
        this.maritalStatus_L1 ;
        this.maritalStatus_L2 ;
        this.maritalStatus_L3 ;
        this.maritalStatus_L4 ;
        this.photo = {};
        this.email ;
        this.cardType ;
        this.cardID ;
        this.cardExpiryDate ;
        this.cI01_Text ;
        this.cI02_Text ;
        this.cI03_Text ;
        this.cI04_Text ;
        this.cI05_Text ;
        this.cI06_Text ;
        this.cI07_Text ;
        this.cI08_Text ;
        this.cI09_Text ;
        this.cI10_Text ;
        this.cI11_Text ;
        this.cI12_Text ;
        this.cI13_Text ;
        this.cI14_Text ;
        this.cI15_Text ;
        this.cI16_Text ;
        this.cI17_Text ;
        this.cI18_Text ;
        this.cI19_Text ;
        this.cI20_Text ;
        this.cI01_Date ;
        this.cI02_Date ;
        this.cI03_Date ;
        this.cI04_Date ;
        this.cI05_Date ;
        this.cI01_Number ;
        this.cI02_Number ;
        this.cI03_Number ;
        this.cI04_Number ;
        this.cI05_Number ;
        this.creationTime ;
        this.lastUpdateTime ;
    }
}
module.exports = customer;


